export const citiesData = {
	"index": {
		"lisboa":1,"vila nova de gaia":2,"porto":3,"braga":4,"matosinhos":5,"amadora":6,"almada":7,"oeiras":8,"gondomar":9,"guimarães":10,"odivelas":11,"coimbra":12,"vila franca de xira":13,"maia":14,"leiria":15,"setúbal":16,"funchal":17,"viseu":18,"valongo":19,"viana do castelo":20,"paredes":21,"vila do conde":22,"torres vedras":23,"barreiro":24,"aveiro":25,"queluz":26,"mafra":27,"penafiel":28,"loulé":29,"ponta delgada":30,"moita":31,"faro":32,"póvoa de varzim":33,"palmela":34,"santarém":35,"figueira da foz":36,"felgueiras":37,"paços de ferreira":38,"amarante":39,"castelo branco":40,"évora":41,"portimão":42,"pombal":43,"marco de canavezes":44,"vila real":45,"covilhã":46,"caldas da rainha":47,"montijo":48,"rio tinto":49,"fafe":50,"sesimbra":51,"amora":52,"vila verde":53,"lousada":54,"ourém":55,"olhão":56,"ponte de lima":57,"santa cruz":58,"guarda":59,"chaves":60,"tomar":61,"ílhavo":62,"trofa":63,"ermezinde":64,"marinha grande":65,"silves":66,"torres novas":67,"beja":68,"agualva":69,"câmara de lobos":70,"angra do heroísmo":71,"bragança":72,"esposende":73,"ribeira grande":74,"espinho":75,"lagos":76,"anadia":77,"benavente":78,"massamá":79,"estarreja":80,"lamego":81,"estoril":82,"montemor-o-velho":83,"tavira":84,"odemira":85,"albergaria-a-velha":86,"portalegre":87,"porto de mós":88,"mirandela":89,"vizela":90,"almeirim":91,"caniço":92,"oliveira do bairro":93,"vale de cambra":94,"póvoa de lanhoso":95,"azambuja":96,"são joão da madeira":97,"cacém":98,"rio maior":99,"praia da vitória":100,"elvas":101,"baião":102,"cinfães":103,"entroncamento":104,"celorico de basto":105,"alfena":106,"soure":107,"monção":108,"vila real de santo antónio":109,"sacavém":110,"lousã":111,"alcochete":112,"montemor-o-novo":113,"peso da régua":114,"condeixa-a-nova":115,"ponte de sôr":116,"cabeceiras de basto":117,"quarteira":118,"sertã":119,"batalha":120,"macedo de cavaleiros":121,"serpa":122,"castro daire":123,"penacova":124,"moura":125,"nazaré":126,"horta":127,"falagueira":128,"cadaval":129,"estremoz":130,"sines":131,"gouveia":132,"nelas":133,"arruda dos vinhos":134,"ribeira brava":135,"bombarral":136,"vila pouca de aguiar":137,"ansião":138,"miranda do corvo":139,"alcácer do sal":140,"vieira do minho":141,"sabugal":142,"mira":143,"sátão":144,"arcozelo":145,"sever do vouga":146,"arganil":147,"tábua":148,"vendas novas":149,"óbidos":150,"calheta":151,"resende":152,"reguengos de monsaraz":153,"valadares":154,"são brás de alportel":155,"murtosa":156,"moimenta da beira":157,"sobral de monte agraço":158,"trancoso":159,"carregal do sal":160,"idanha-a-nova":161,"pinhel":162,"aljustrel":163,"melgaço":164,"vinhais":165,"almargem":166,"aver-o-mar":167,"ponta do sol":168,"ferreira do zêzere":169,"torre de moncorvo":170,"campo maior":171,"argoncilhe":172,"vila viçosa":173,"proença-a-nova":174,"tarouca":175,"penalva do castelo":176,"são joão da pesqueira":177,"santana":178,"alpiarça":179,"celorico da beira":180,"joane":181,"mondim de basto":182,"miranda do douro":183,"nisa":184,"arraiolos":185,"santa marta de penaguião":186,"borba":187,"vila nova da barquinha":188,"vila nova de foz côa":189,"castelões de cepeda":190,"poiares":191,"castro verde":192,"mértola":193,"terras de bouro":194,"redondo":195,"castro marim":196,"ribeira de pena":197,"portel":198,"carrazeda de anciães":199,"sabrosa":200,"tabuaço":201,"povoação":202,"armamar":203,"figueira de castelo rodrigo":204,"são martinho":205,"figueiró dos vinhos":206,"madalena":207,"monchique":208,"penela":209,"murça":210,"vidigueira":211,"olival":212,"viana do alentejo":213,"oleiros":214,"penamacor":215,"vila do porto":216,"aguiar da beira":217,"golegã":218,"riachos":219,"velas":220,"ourique":221,"vila do bispo":222,"vila nova de paiva":223,"terrujem":224,"sousel":225,"fornos de algodres":226,"mora":227,"caranguejeira":228,"nordeste":229,"cuba":230,"pampilhosa da serra":231,"lajes":232,"vimioso":233,"avis":234,"mesão frio":235,"valpaços":236,"góis":237,"vila nova de milfontes":238,"constância":239,"sardoal":240,"arcozelo":241,"lorvão":242,"pedrógão grande":243,"freixo de espada à cinta":244,"calheta":245,"armação de pêra":246,"vila velha de ródão":247,"marvão":248,"vila de rei":249,"manteigas":250,"riba de ave":251,"fronteira":252,"castelo de vide":253,"são roque do pico":254,"monforte":255,"valado de frades":256,"castanheira de pêra":257,"arronches":258,"são vicente":259,"trouxemil":260,"ferreiros":261,"carvoeiro":262,"porto moniz":263,"mourão":264,"barrancos":265,"caminha":266,"boticas":267,"barcelos":268,"loures":269,"santo tirso":270,"famalicão":271,"cartaxo":272,"fundão":273,"oliveira de azemeis":274,"ovar":275,"lagoa":276,"albufeira":277,"sintra":278,"águeda":279,"peniche":280,"salvaterra de magos":281,"cascais":282,"ponte da barca":283,"almodôvar":284,"alcobaça":285,"oliveira do hospital":286,"abrantes":287,"santiago do cacém":288,"cantanhede":289,"grândola":290,"mangualde":291,"arouca":292,"feira":293,"seia":294,"coruche":295,"chamusca":296,"crato":297,"belmonte":298,"vagos":299,"tondela":300,"gavião":301,"santa comba dão":302,"alandroal":303,"mogadouro":304,"paredes de coura":305,"seixal":306,"amares":307,"alenquer":308,"mêda":309,"vouzela":310,"mação":311,"alfândega da fé":312,"são pedro do sul":313,"trofa":314,"alter do chão":315,"mortágua":316,"vila nova de cerveira":317,"arcos de valdevez":318,"alcanena":319,"mealhada":320,"valença":321,"sernancelhe":322,"vila flor":323,"castelo de paiva":324,"penedono":325,"alijó":326,"oliveira de frades":327,"vizela":328,"alvaiázere":329,"montalegre":330,"alvito":331,"alcoutim":332,"almeida":333,"aljezur":334,"lourinhã":335,"ferreira do alentejo":336,
	},
	"data": [
		{
			"city": "Lisbon", 
			"lat": "38.7452", 
			"lng": "-9.1604", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "primary", 
			"population": "506654", 
			"population_proper": "506654"
		}, 
		{
			"city": "Vila Nova de Gaia", 
			"lat": "41.1333", 
			"lng": "-8.6167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "minor", 
			"population": "302295", 
			"population_proper": "302295"
		}, 
		{
			"city": "Porto", 
			"lat": "41.1495", 
			"lng": "-8.6108", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "admin", 
			"population": "237591", 
			"population_proper": "237591"
		}, 
		{
			"city": "Braga", 
			"lat": "41.5333", 
			"lng": "-8.4167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "admin", 
			"population": "181494", 
			"population_proper": "181494"
		}, 
		{
			"city": "Matosinhos", 
			"lat": "41.2077", 
			"lng": "-8.6674", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "minor", 
			"population": "175478", 
			"population_proper": "175478"
		}, 
		{
			"city": "Amadora", 
			"lat": "38.7500", 
			"lng": "-9.2333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "minor", 
			"population": "175136", 
			"population_proper": "175136"
		}, 
		{
			"city": "Almada", 
			"lat": "38.6803", 
			"lng": "-9.1583", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Set\u00fabal", 
			"capital": "minor", 
			"population": "174030", 
			"population_proper": "174030"
		}, 
		{
			"city": "Oeiras", 
			"lat": "38.6970", 
			"lng": "-9.3017", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "minor", 
			"population": "172120", 
			"population_proper": "172120"
		}, 
		{
			"city": "Gondomar", 
			"lat": "41.1500", 
			"lng": "-8.5333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "minor", 
			"population": "168027", 
			"population_proper": "168027"
		}, 
		{
			"city": "Guimar\u00e3es", 
			"lat": "41.4450", 
			"lng": "-8.2908", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "minor", 
			"population": "158124", 
			"population_proper": "158124"
		}, 
		{
			"city": "Odivelas", 
			"lat": "38.8000", 
			"lng": "-9.1833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "minor", 
			"population": "144549", 
			"population_proper": "144549"
		}, 
		{
			"city": "Coimbra", 
			"lat": "40.2111", 
			"lng": "-8.4291", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "admin", 
			"population": "143396", 
			"population_proper": "143396"
		}, 
		{
			"city": "Vila Franca de Xira", 
			"lat": "38.9500", 
			"lng": "-8.9833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "minor", 
			"population": "136886", 
			"population_proper": "136886"
		}, 
		{
			"city": "Maia", 
			"lat": "41.2333", 
			"lng": "-8.6167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "minor", 
			"population": "135306", 
			"population_proper": "135306"
		}, 
		{
			"city": "Leiria", 
			"lat": "39.7431", 
			"lng": "-8.8069", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "admin", 
			"population": "126897", 
			"population_proper": "126897"
		}, 
		{
			"city": "Set\u00fabal", 
			"lat": "38.5243", 
			"lng": "-8.8926", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Set\u00fabal", 
			"capital": "admin", 
			"population": "121185", 
			"population_proper": "121185"
		}, 
		{
			"city": "Funchal", 
			"lat": "32.6500", 
			"lng": "-16.9167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Madeira", 
			"capital": "admin", 
			"population": "111892", 
			"population_proper": "111892"
		}, 
		{
			"city": "Viseu", 
			"lat": "40.6667", 
			"lng": "-7.9167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "admin", 
			"population": "99274", 
			"population_proper": "99274"
		}, 
		{
			"city": "Valongo", 
			"lat": "41.1833", 
			"lng": "-8.5000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "minor", 
			"population": "93858", 
			"population_proper": "93858"
		}, 
		{
			"city": "Viana do Castelo", 
			"lat": "41.7000", 
			"lng": "-8.8333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viana do Castelo", 
			"capital": "admin", 
			"population": "88725", 
			"population_proper": "88725"
		}, 
		{
			"city": "Paredes", 
			"lat": "41.2000", 
			"lng": "-8.3333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "minor", 
			"population": "86854", 
			"population_proper": "86854"
		}, 
		{
			"city": "Vila do Conde", 
			"lat": "41.3500", 
			"lng": "-8.7500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "minor", 
			"population": "79533", 
			"population_proper": "79533"
		}, 
		{
			"city": "Torres Vedras", 
			"lat": "39.0833", 
			"lng": "-9.2667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "minor", 
			"population": "79465", 
			"population_proper": "79465"
		}, 
		{
			"city": "Barreiro", 
			"lat": "38.6609", 
			"lng": "-9.0733", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Set\u00fabal", 
			"capital": "minor", 
			"population": "78764", 
			"population_proper": "78764"
		}, 
		{
			"city": "Aveiro", 
			"lat": "40.6389", 
			"lng": "-8.6553", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "admin", 
			"population": "78450", 
			"population_proper": "78450"
		}, 
		{
			"city": "Queluz", 
			"lat": "38.7566", 
			"lng": "-9.2545", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "", 
			"population": "78273", 
			"population_proper": "78273"
		}, 
		{
			"city": "Mafra", 
			"lat": "38.9333", 
			"lng": "-9.3333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "minor", 
			"population": "76685", 
			"population_proper": "76685"
		}, 
		{
			"city": "Penafiel", 
			"lat": "41.2000", 
			"lng": "-8.2833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "minor", 
			"population": "72265", 
			"population_proper": "72265"
		}, 
		{
			"city": "Loul\u00e9", 
			"lat": "37.1440", 
			"lng": "-8.0235", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "minor", 
			"population": "70622", 
			"population_proper": "70622"
		}, 
		{
			"city": "Ponta Delgada", 
			"lat": "37.7400", 
			"lng": "-25.6700", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Azores", 
			"capital": "admin", 
			"population": "68809", 
			"population_proper": "68809"
		}, 
		{
			"city": "Moita", 
			"lat": "38.6500", 
			"lng": "-8.9833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Set\u00fabal", 
			"capital": "minor", 
			"population": "66029", 
			"population_proper": "66029"
		}, 
		{
			"city": "Faro", 
			"lat": "37.0167", 
			"lng": "-7.9333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "admin", 
			"population": "64560", 
			"population_proper": "64560"
		}, 
		{
			"city": "P\u00f3voa de Varzim", 
			"lat": "41.3916", 
			"lng": "-8.7571", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "minor", 
			"population": "63408", 
			"population_proper": "63408"
		}, 
		{
			"city": "Palmela", 
			"lat": "38.5667", 
			"lng": "-8.9000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Set\u00fabal", 
			"capital": "minor", 
			"population": "62831", 
			"population_proper": "62831"
		}, 
		{
			"city": "Santar\u00e9m", 
			"lat": "39.2369", 
			"lng": "-8.6850", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "admin", 
			"population": "62200", 
			"population_proper": "62200"
		}, 
		{
			"city": "Figueira da Foz", 
			"lat": "40.1508", 
			"lng": "-8.8618", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "minor", 
			"population": "62125", 
			"population_proper": "62125"
		}, 
		{
			"city": "Felgueiras", 
			"lat": "41.3667", 
			"lng": "-8.1833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "minor", 
			"population": "58065", 
			"population_proper": "58065"
		}, 
		{
			"city": "Pa\u00e7os de Ferreira", 
			"lat": "41.2833", 
			"lng": "-8.3833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "minor", 
			"population": "56340", 
			"population_proper": "56340"
		}, 
		{
			"city": "Amarante", 
			"lat": "41.2667", 
			"lng": "-8.0833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "minor", 
			"population": "56264", 
			"population_proper": "56264"
		}, 
		{
			"city": "Castelo Branco", 
			"lat": "39.8230", 
			"lng": "-7.4931", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Castelo Branco", 
			"capital": "admin", 
			"population": "56109", 
			"population_proper": "56109"
		}, 
		{
			"city": "\u00c9vora", 
			"lat": "38.5667", 
			"lng": "-7.9000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "\u00c9vora", 
			"capital": "admin", 
			"population": "55620", 
			"population_proper": "55620"
		}, 
		{
			"city": "Portim\u00e3o", 
			"lat": "37.1333", 
			"lng": "-8.5333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "minor", 
			"population": "55614", 
			"population_proper": "55614"
		}, 
		{
			"city": "Pombal", 
			"lat": "39.9162", 
			"lng": "-8.6279", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "minor", 
			"population": "55217", 
			"population_proper": "55217"
		}, 
		{
			"city": "Marco de Canavezes", 
			"lat": "41.1833", 
			"lng": "-8.1500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "minor", 
			"population": "53450", 
			"population_proper": "53450"
		}, 
		{
			"city": "Vila Real", 
			"lat": "41.3002", 
			"lng": "-7.7398", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Vila Real", 
			"capital": "admin", 
			"population": "51850", 
			"population_proper": "51850"
		}, 
		{
			"city": "Covilh\u00e3", 
			"lat": "40.2833", 
			"lng": "-7.5000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Castelo Branco", 
			"capital": "minor", 
			"population": "51797", 
			"population_proper": "51797"
		}, 
		{
			"city": "Caldas da Rainha", 
			"lat": "39.4069", 
			"lng": "-9.1363", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "minor", 
			"population": "51729", 
			"population_proper": "51729"
		}, 
		{
			"city": "Montijo", 
			"lat": "38.7049", 
			"lng": "-8.9757", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Set\u00fabal", 
			"capital": "minor", 
			"population": "51222", 
			"population_proper": "51222"
		}, 
		{
			"city": "Rio Tinto", 
			"lat": "41.1833", 
			"lng": "-8.5667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "", 
			"population": "50713", 
			"population_proper": "50713"
		}, 
		{
			"city": "Fafe", 
			"lat": "41.4500", 
			"lng": "-8.1667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "minor", 
			"population": "50633", 
			"population_proper": "50633"
		}, 
		{
			"city": "Sesimbra", 
			"lat": "38.4437", 
			"lng": "-9.0996", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Set\u00fabal", 
			"capital": "minor", 
			"population": "49500", 
			"population_proper": "49500"
		}, 
		{
			"city": "Amora", 
			"lat": "38.6265", 
			"lng": "-9.1189", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Set\u00fabal", 
			"capital": "", 
			"population": "48629", 
			"population_proper": "48629"
		}, 
		{
			"city": "Vila Verde", 
			"lat": "41.6500", 
			"lng": "-8.4333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "minor", 
			"population": "47888", 
			"population_proper": "47888"
		}, 
		{
			"city": "Lousada", 
			"lat": "41.2833", 
			"lng": "-8.2833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "minor", 
			"population": "47387", 
			"population_proper": "47387"
		}, 
		{
			"city": "Our\u00e9m", 
			"lat": "39.6500", 
			"lng": "-8.5833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "45932", 
			"population_proper": "45932"
		}, 
		{
			"city": "Olh\u00e3o", 
			"lat": "37.0278", 
			"lng": "-7.8389", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "minor", 
			"population": "45396", 
			"population_proper": "45396"
		}, 
		{
			"city": "Ponte de Lima", 
			"lat": "41.7667", 
			"lng": "-8.5833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viana do Castelo", 
			"capital": "minor", 
			"population": "43498", 
			"population_proper": "43498"
		}, 
		{
			"city": "Santa Cruz", 
			"lat": "32.6750", 
			"lng": "-16.8309", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Madeira", 
			"capital": "", 
			"population": "43005", 
			"population_proper": "43005"
		}, 
		{
			"city": "Guarda", 
			"lat": "40.5364", 
			"lng": "-7.2683", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Guarda", 
			"capital": "admin", 
			"population": "42541", 
			"population_proper": "42541"
		}, 
		{
			"city": "Chaves", 
			"lat": "41.7399", 
			"lng": "-7.4707", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Vila Real", 
			"capital": "minor", 
			"population": "41243", 
			"population_proper": "41243"
		}, 
		{
			"city": "Tomar", 
			"lat": "39.6000", 
			"lng": "-8.4167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "40677", 
			"population_proper": "40677"
		}, 
		{
			"city": "\u00cdlhavo", 
			"lat": "40.6000", 
			"lng": "-8.6667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "40349", 
			"population_proper": "40349"
		}, 
		{
			"city": "Trofa", 
			"lat": "41.3374", 
			"lng": "-8.5596", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "minor", 
			"population": "38999", 
			"population_proper": "38999"
		}, 
		{
			"city": "Ermezinde", 
			"lat": "41.2133", 
			"lng": "-8.5472", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "", 
			"population": "38798", 
			"population_proper": "38798"
		}, 
		{
			"city": "Marinha Grande", 
			"lat": "39.7500", 
			"lng": "-8.9333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "minor", 
			"population": "38681", 
			"population_proper": "38681"
		}, 
		{
			"city": "Silves", 
			"lat": "37.1833", 
			"lng": "-8.4333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "minor", 
			"population": "37126", 
			"population_proper": "37126"
		}, 
		{
			"city": "Torres Novas", 
			"lat": "39.4833", 
			"lng": "-8.5333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "36717", 
			"population_proper": "36717"
		}, 
		{
			"city": "Beja", 
			"lat": "38.0333", 
			"lng": "-7.8833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Beja", 
			"capital": "admin", 
			"population": "35854", 
			"population_proper": "35854"
		}, 
		{
			"city": "Agualva", 
			"lat": "38.7700", 
			"lng": "-9.2988", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "", 
			"population": "35824", 
			"population_proper": "35824"
		}, 
		{
			"city": "C\u00e2mara de Lobos", 
			"lat": "32.6500", 
			"lng": "-16.9667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Madeira", 
			"capital": "", 
			"population": "35666", 
			"population_proper": "35666"
		}, 
		{
			"city": "Angra do Hero\u00edsmo", 
			"lat": "38.6558", 
			"lng": "-27.2153", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Azores", 
			"capital": "", 
			"population": "35402", 
			"population_proper": "35402"
		}, 
		{
			"city": "Bragan\u00e7a", 
			"lat": "41.8000", 
			"lng": "-6.7500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Bragan\u00e7a", 
			"capital": "admin", 
			"population": "35341", 
			"population_proper": "35341"
		}, 
		{
			"city": "Esposende", 
			"lat": "41.5333", 
			"lng": "-8.7833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "minor", 
			"population": "34254", 
			"population_proper": "34254"
		}, 
		{
			"city": "Ribeira Grande", 
			"lat": "37.8167", 
			"lng": "-25.5167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Azores", 
			"capital": "", 
			"population": "32112", 
			"population_proper": "32112"
		}, 
		{
			"city": "Espinho", 
			"lat": "41.0100", 
			"lng": "-8.6400", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "31786", 
			"population_proper": "31786"
		}, 
		{
			"city": "Lagos", 
			"lat": "37.1000", 
			"lng": "-8.6667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "minor", 
			"population": "31049", 
			"population_proper": "31049"
		}, 
		{
			"city": "Anadia", 
			"lat": "40.4333", 
			"lng": "-8.4333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "29150", 
			"population_proper": "29150"
		}, 
		{
			"city": "Benavente", 
			"lat": "38.9833", 
			"lng": "-8.8167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "29019", 
			"population_proper": "29019"
		}, 
		{
			"city": "Massam\u00e1", 
			"lat": "38.7568", 
			"lng": "-9.2748", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "", 
			"population": "28112", 
			"population_proper": "28112"
		}, 
		{
			"city": "Estarreja", 
			"lat": "40.7500", 
			"lng": "-8.5667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "26997", 
			"population_proper": "26997"
		}, 
		{
			"city": "Lamego", 
			"lat": "41.0833", 
			"lng": "-7.8667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "26691", 
			"population_proper": "26691"
		}, 
		{
			"city": "Estoril", 
			"lat": "38.7057", 
			"lng": "-9.3977", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "", 
			"population": "26399", 
			"population_proper": "26399"
		}, 
		{
			"city": "Montemor-o-Velho", 
			"lat": "40.1667", 
			"lng": "-8.6833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "minor", 
			"population": "26171", 
			"population_proper": "26171"
		}, 
		{
			"city": "Tavira", 
			"lat": "37.1309", 
			"lng": "-7.6506", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "minor", 
			"population": "26167", 
			"population_proper": "26167"
		}, 
		{
			"city": "Odemira", 
			"lat": "37.5833", 
			"lng": "-8.6333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Beja", 
			"capital": "minor", 
			"population": "26066", 
			"population_proper": "26066"
		}, 
		{
			"city": "Albergaria-a-Velha", 
			"lat": "40.6936", 
			"lng": "-8.4806", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "25252", 
			"population_proper": "25252"
		}, 
		{
			"city": "Portalegre", 
			"lat": "39.3167", 
			"lng": "-7.4167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Portalegre", 
			"capital": "admin", 
			"population": "24930", 
			"population_proper": "24930"
		}, 
		{
			"city": "Porto de M\u00f3s", 
			"lat": "39.6000", 
			"lng": "-8.8167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "minor", 
			"population": "24342", 
			"population_proper": "24342"
		}, 
		{
			"city": "Mirandela", 
			"lat": "41.4833", 
			"lng": "-7.1833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Bragan\u00e7a", 
			"capital": "minor", 
			"population": "23850", 
			"population_proper": "23850"
		}, 
		{
			"city": "Vizela", 
			"lat": "41.3833", 
			"lng": "-8.3000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "", 
			"population": "23736", 
			"population_proper": "23736"
		}, 
		{
			"city": "Almeirim", 
			"lat": "39.2167", 
			"lng": "-8.6333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "23376", 
			"population_proper": "23376"
		}, 
		{
			"city": "Cani\u00e7o", 
			"lat": "32.6412", 
			"lng": "-16.8504", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Madeira", 
			"capital": "", 
			"population": "23361", 
			"population_proper": "23361"
		}, 
		{
			"city": "Oliveira do Bairro", 
			"lat": "40.5167", 
			"lng": "-8.5000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "23028", 
			"population_proper": "23028"
		}, 
		{
			"city": "Vale de Cambra", 
			"lat": "40.8500", 
			"lng": "-8.4000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "22864", 
			"population_proper": "22864"
		}, 
		{
			"city": "P\u00f3voa de Lanhoso", 
			"lat": "41.5667", 
			"lng": "-8.2667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "minor", 
			"population": "21886", 
			"population_proper": "21886"
		}, 
		{
			"city": "Azambuja", 
			"lat": "39.0667", 
			"lng": "-8.8667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "minor", 
			"population": "21814", 
			"population_proper": "21814"
		}, 
		{
			"city": "S\u00e3o Jo\u00e3o da Madeira", 
			"lat": "40.9000", 
			"lng": "-8.5000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "21713", 
			"population_proper": "21713"
		}, 
		{
			"city": "Cac\u00e9m", 
			"lat": "38.7704", 
			"lng": "-9.3081", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "", 
			"population": "21289", 
			"population_proper": "21289"
		}, 
		{
			"city": "Rio Maior", 
			"lat": "39.3333", 
			"lng": "-8.9333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "21192", 
			"population_proper": "21192"
		}, 
		{
			"city": "Praia da Vit\u00f3ria", 
			"lat": "38.7333", 
			"lng": "-27.0667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Azores", 
			"capital": "", 
			"population": "21035", 
			"population_proper": "21035"
		}, 
		{
			"city": "Elvas", 
			"lat": "38.8800", 
			"lng": "-7.1628", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Portalegre", 
			"capital": "minor", 
			"population": "20706", 
			"population_proper": "20706"
		}, 
		{
			"city": "Bai\u00e3o", 
			"lat": "41.1667", 
			"lng": "-8.0333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "minor", 
			"population": "20522", 
			"population_proper": "20522"
		}, 
		{
			"city": "Cinf\u00e3es", 
			"lat": "41.0667", 
			"lng": "-8.0833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "20427", 
			"population_proper": "20427"
		}, 
		{
			"city": "Entroncamento", 
			"lat": "39.4667", 
			"lng": "-8.4667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "20206", 
			"population_proper": "20206"
		}, 
		{
			"city": "Celorico de Basto", 
			"lat": "41.3869", 
			"lng": "-8.0022", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "minor", 
			"population": "20098", 
			"population_proper": "20098"
		}, 
		{
			"city": "Alfena", 
			"lat": "41.2395", 
			"lng": "-8.5244", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "", 
			"population": "20000", 
			"population_proper": "20000"
		}, 
		{
			"city": "Soure", 
			"lat": "40.0500", 
			"lng": "-8.6333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "minor", 
			"population": "19245", 
			"population_proper": "19245"
		}, 
		{
			"city": "Mon\u00e7\u00e3o", 
			"lat": "42.0733", 
			"lng": "-8.4800", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viana do Castelo", 
			"capital": "minor", 
			"population": "19230", 
			"population_proper": "19230"
		}, 
		{
			"city": "Vila Real de Santo Ant\u00f3nio", 
			"lat": "37.2000", 
			"lng": "-7.4167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "minor", 
			"population": "19156", 
			"population_proper": "19156"
		}, 
		{
			"city": "Sacav\u00e9m", 
			"lat": "38.7944", 
			"lng": "-9.1053", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "", 
			"population": "18469", 
			"population_proper": "18469"
		}, 
		{
			"city": "Lous\u00e3", 
			"lat": "40.1125", 
			"lng": "-8.2469", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "minor", 
			"population": "17604", 
			"population_proper": "17604"
		}, 
		{
			"city": "Alcochete", 
			"lat": "38.7553", 
			"lng": "-8.9608", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Set\u00fabal", 
			"capital": "minor", 
			"population": "17569", 
			"population_proper": "17569"
		}, 
		{
			"city": "Montemor-o-Novo", 
			"lat": "38.6500", 
			"lng": "-8.2167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "\u00c9vora", 
			"capital": "minor", 
			"population": "17437", 
			"population_proper": "17437"
		}, 
		{
			"city": "Peso da R\u00e9gua", 
			"lat": "41.1632", 
			"lng": "-7.7890", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Vila Real", 
			"capital": "minor", 
			"population": "17131", 
			"population_proper": "17131"
		}, 
		{
			"city": "Condeixa-a-Nova", 
			"lat": "40.1167", 
			"lng": "-8.5000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "minor", 
			"population": "17078", 
			"population_proper": "17078"
		}, 
		{
			"city": "Ponte de S\u00f4r", 
			"lat": "39.2500", 
			"lng": "-8.0167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Portalegre", 
			"capital": "minor", 
			"population": "16722", 
			"population_proper": "16722"
		}, 
		{
			"city": "Cabeceiras de Basto", 
			"lat": "41.5167", 
			"lng": "-8.0000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "minor", 
			"population": "16710", 
			"population_proper": "16710"
		}, 
		{
			"city": "Quarteira", 
			"lat": "37.0695", 
			"lng": "-8.1006", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "", 
			"population": "16131", 
			"population_proper": "16131"
		}, 
		{
			"city": "Sert\u00e3", 
			"lat": "39.8008", 
			"lng": "-8.1003", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Castelo Branco", 
			"capital": "minor", 
			"population": "15880", 
			"population_proper": "15880"
		}, 
		{
			"city": "Batalha", 
			"lat": "39.6500", 
			"lng": "-8.8167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "minor", 
			"population": "15805", 
			"population_proper": "15805"
		}, 
		{
			"city": "Macedo de Cavaleiros", 
			"lat": "41.5333", 
			"lng": "-6.9500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Bragan\u00e7a", 
			"capital": "minor", 
			"population": "15776", 
			"population_proper": "15776"
		}, 
		{
			"city": "Serpa", 
			"lat": "37.9333", 
			"lng": "-7.5833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Beja", 
			"capital": "minor", 
			"population": "15623", 
			"population_proper": "15623"
		}, 
		{
			"city": "Castro Daire", 
			"lat": "40.9000", 
			"lng": "-7.9333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "15339", 
			"population_proper": "15339"
		}, 
		{
			"city": "Penacova", 
			"lat": "40.2667", 
			"lng": "-8.2667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "minor", 
			"population": "15251", 
			"population_proper": "15251"
		}, 
		{
			"city": "Moura", 
			"lat": "38.1397", 
			"lng": "-7.4505", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Beja", 
			"capital": "minor", 
			"population": "15167", 
			"population_proper": "15167"
		}, 
		{
			"city": "Nazar\u00e9", 
			"lat": "39.6000", 
			"lng": "-9.0667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "minor", 
			"population": "15158", 
			"population_proper": "15158"
		}, 
		{
			"city": "Horta", 
			"lat": "38.5333", 
			"lng": "-28.6333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Azores", 
			"capital": "", 
			"population": "14994", 
			"population_proper": "14994"
		}, 
		{
			"city": "Falagueira", 
			"lat": "38.7590", 
			"lng": "-9.2199", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "", 
			"population": "14530", 
			"population_proper": "14530"
		}, 
		{
			"city": "Cadaval", 
			"lat": "39.2500", 
			"lng": "-9.1000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "minor", 
			"population": "14525", 
			"population_proper": "14525"
		}, 
		{
			"city": "Estremoz", 
			"lat": "38.8422", 
			"lng": "-7.5881", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "\u00c9vora", 
			"capital": "minor", 
			"population": "14318", 
			"population_proper": "14318"
		}, 
		{
			"city": "Sines", 
			"lat": "37.9536", 
			"lng": "-8.8712", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Set\u00fabal", 
			"capital": "minor", 
			"population": "14238", 
			"population_proper": "14238"
		}, 
		{
			"city": "Gouveia", 
			"lat": "40.5000", 
			"lng": "-7.6000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Guarda", 
			"capital": "minor", 
			"population": "14046", 
			"population_proper": "14046"
		}, 
		{
			"city": "Nelas", 
			"lat": "40.5167", 
			"lng": "-7.8500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "14037", 
			"population_proper": "14037"
		}, 
		{
			"city": "Arruda dos Vinhos", 
			"lat": "38.9833", 
			"lng": "-9.0667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "minor", 
			"population": "13391", 
			"population_proper": "13391"
		}, 
		{
			"city": "Ribeira Brava", 
			"lat": "32.6722", 
			"lng": "-17.0639", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Madeira", 
			"capital": "", 
			"population": "13375", 
			"population_proper": "13375"
		}, 
		{
			"city": "Bombarral", 
			"lat": "39.2667", 
			"lng": "-9.1500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "minor", 
			"population": "13193", 
			"population_proper": "13193"
		}, 
		{
			"city": "Vila Pouca de Aguiar", 
			"lat": "41.4833", 
			"lng": "-7.6333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Vila Real", 
			"capital": "minor", 
			"population": "13187", 
			"population_proper": "13187"
		}, 
		{
			"city": "Ansi\u00e3o", 
			"lat": "39.9167", 
			"lng": "-8.4333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "minor", 
			"population": "13128", 
			"population_proper": "13128"
		}, 
		{
			"city": "Miranda do Corvo", 
			"lat": "40.1000", 
			"lng": "-8.3333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "minor", 
			"population": "13098", 
			"population_proper": "13098"
		}, 
		{
			"city": "Alc\u00e1cer do Sal", 
			"lat": "38.3725", 
			"lng": "-8.5133", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Set\u00fabal", 
			"capital": "minor", 
			"population": "13046", 
			"population_proper": "13046"
		}, 
		{
			"city": "Vieira do Minho", 
			"lat": "41.6333", 
			"lng": "-8.1333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "minor", 
			"population": "12997", 
			"population_proper": "12997"
		}, 
		{
			"city": "Sabugal", 
			"lat": "40.3500", 
			"lng": "-7.0833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Guarda", 
			"capital": "minor", 
			"population": "12544", 
			"population_proper": "12544"
		}, 
		{
			"city": "Mira", 
			"lat": "40.4285", 
			"lng": "-8.7363", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "minor", 
			"population": "12465", 
			"population_proper": "12465"
		}, 
		{
			"city": "S\u00e1t\u00e3o", 
			"lat": "40.7333", 
			"lng": "-7.7167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "12444", 
			"population_proper": "12444"
		}, 
		{
			"city": "Arcozelo", 
			"lat": "41.0555", 
			"lng": "-8.6395", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "", 
			"population": "12393", 
			"population_proper": "12393"
		}, 
		{
			"city": "Sever do Vouga", 
			"lat": "40.7167", 
			"lng": "-8.3667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "12356", 
			"population_proper": "12356"
		}, 
		{
			"city": "Arganil", 
			"lat": "40.2167", 
			"lng": "-8.0500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "minor", 
			"population": "12145", 
			"population_proper": "12145"
		}, 
		{
			"city": "T\u00e1bua", 
			"lat": "40.3667", 
			"lng": "-8.0333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "minor", 
			"population": "12071", 
			"population_proper": "12071"
		}, 
		{
			"city": "Vendas Novas", 
			"lat": "38.6833", 
			"lng": "-8.4500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "\u00c9vora", 
			"capital": "minor", 
			"population": "11846", 
			"population_proper": "11846"
		}, 
		{
			"city": "\u00d3bidos", 
			"lat": "39.3585", 
			"lng": "-9.1760", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "minor", 
			"population": "11689", 
			"population_proper": "11689"
		}, 
		{
			"city": "Calheta", 
			"lat": "32.7333", 
			"lng": "-17.1667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Madeira", 
			"capital": "", 
			"population": "11521", 
			"population_proper": "11521"
		}, 
		{
			"city": "Resende", 
			"lat": "41.1000", 
			"lng": "-7.9500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "11364", 
			"population_proper": "11364"
		}, 
		{
			"city": "Reguengos de Monsaraz", 
			"lat": "38.4167", 
			"lng": "-7.5333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "\u00c9vora", 
			"capital": "minor", 
			"population": "10828", 
			"population_proper": "10828"
		}, 
		{
			"city": "Valadares", 
			"lat": "41.0997", 
			"lng": "-8.6403", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "", 
			"population": "10678", 
			"population_proper": "10678"
		}, 
		{
			"city": "S\u00e3o Br\u00e1s de Alportel", 
			"lat": "37.1500", 
			"lng": "-7.8833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "minor", 
			"population": "10662", 
			"population_proper": "10662"
		}, 
		{
			"city": "Murtosa", 
			"lat": "40.7369", 
			"lng": "-8.6386", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "10585", 
			"population_proper": "10585"
		}, 
		{
			"city": "Moimenta da Beira", 
			"lat": "40.9819", 
			"lng": "-7.6158", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "10212", 
			"population_proper": "10212"
		}, 
		{
			"city": "Sobral de Monte Agra\u00e7o", 
			"lat": "39.0167", 
			"lng": "-9.1500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "minor", 
			"population": "10156", 
			"population_proper": "10156"
		}, 
		{
			"city": "Trancoso", 
			"lat": "40.7833", 
			"lng": "-7.3500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Guarda", 
			"capital": "minor", 
			"population": "9878", 
			"population_proper": "9878"
		}, 
		{
			"city": "Carregal do Sal", 
			"lat": "40.4333", 
			"lng": "-8.0000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "", 
			"population": "9835", 
			"population_proper": "9835"
		}, 
		{
			"city": "Idanha-a-Nova", 
			"lat": "39.9167", 
			"lng": "-7.2333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Castelo Branco", 
			"capital": "minor", 
			"population": "9716", 
			"population_proper": "9716"
		}, 
		{
			"city": "Pinhel", 
			"lat": "40.7833", 
			"lng": "-7.0667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Guarda", 
			"capital": "minor", 
			"population": "9627", 
			"population_proper": "9627"
		}, 
		{
			"city": "Aljustrel", 
			"lat": "37.8785", 
			"lng": "-8.1614", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Beja", 
			"capital": "minor", 
			"population": "9257", 
			"population_proper": "9257"
		}, 
		{
			"city": "Melga\u00e7o", 
			"lat": "42.1167", 
			"lng": "-8.2667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viana do Castelo", 
			"capital": "minor", 
			"population": "9213", 
			"population_proper": "9213"
		}, 
		{
			"city": "Vinhais", 
			"lat": "41.8167", 
			"lng": "-7.0000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Bragan\u00e7a", 
			"capital": "minor", 
			"population": "9066", 
			"population_proper": "9066"
		}, 
		{
			"city": "Almargem", 
			"lat": "38.8475", 
			"lng": "-9.2714", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "", 
			"population": "8983", 
			"population_proper": "8983"
		}, 
		{
			"city": "Aver-o-Mar", 
			"lat": "41.4039", 
			"lng": "-8.7690", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "", 
			"population": "8961", 
			"population_proper": "8961"
		}, 
		{
			"city": "Ponta do Sol", 
			"lat": "32.6811", 
			"lng": "-17.1042", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Madeira", 
			"capital": "", 
			"population": "8862", 
			"population_proper": "8862"
		}, 
		{
			"city": "Ferreira do Z\u00eazere", 
			"lat": "39.7000", 
			"lng": "-8.2833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "8619", 
			"population_proper": "8619"
		}, 
		{
			"city": "Torre de Moncorvo", 
			"lat": "41.2000", 
			"lng": "-7.1333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Bragan\u00e7a", 
			"capital": "minor", 
			"population": "8572", 
			"population_proper": "8572"
		}, 
		{
			"city": "Campo Maior", 
			"lat": "39.0167", 
			"lng": "-7.0667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Portalegre", 
			"capital": "minor", 
			"population": "8456", 
			"population_proper": "8456"
		}, 
		{
			"city": "Argoncilhe", 
			"lat": "41.0167", 
			"lng": "-8.5500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "", 
			"population": "8420", 
			"population_proper": "8420"
		}, 
		{
			"city": "Vila Vi\u00e7osa", 
			"lat": "38.7500", 
			"lng": "-7.4333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "\u00c9vora", 
			"capital": "minor", 
			"population": "8319", 
			"population_proper": "8319"
		}, 
		{
			"city": "Proen\u00e7a-a-Nova", 
			"lat": "39.7500", 
			"lng": "-7.9167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Castelo Branco", 
			"capital": "minor", 
			"population": "8314", 
			"population_proper": "8314"
		}, 
		{
			"city": "Tarouca", 
			"lat": "41.0167", 
			"lng": "-7.7833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "8048", 
			"population_proper": "8048"
		}, 
		{
			"city": "Penalva do Castelo", 
			"lat": "40.6667", 
			"lng": "-7.6833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "7956", 
			"population_proper": "7956"
		}, 
		{
			"city": "S\u00e3o Jo\u00e3o da Pesqueira", 
			"lat": "41.1333", 
			"lng": "-7.4000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "7874", 
			"population_proper": "7874"
		}, 
		{
			"city": "Santana", 
			"lat": "32.8000", 
			"lng": "-16.8667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Madeira", 
			"capital": "", 
			"population": "7719", 
			"population_proper": "7719"
		}, 
		{
			"city": "Alpiar\u00e7a", 
			"lat": "39.2593", 
			"lng": "-8.5850", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "7702", 
			"population_proper": "7702"
		}, 
		{
			"city": "Celorico da Beira", 
			"lat": "40.6333", 
			"lng": "-7.4000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Guarda", 
			"capital": "minor", 
			"population": "7693", 
			"population_proper": "7693"
		}, 
		{
			"city": "Joane", 
			"lat": "41.4333", 
			"lng": "-8.4167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "", 
			"population": "7528", 
			"population_proper": "7528"
		}, 
		{
			"city": "Mondim de Basto", 
			"lat": "41.4000", 
			"lng": "-7.9500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Vila Real", 
			"capital": "minor", 
			"population": "7493", 
			"population_proper": "7493"
		}, 
		{
			"city": "Miranda do Douro", 
			"lat": "41.5000", 
			"lng": "-6.2667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Bragan\u00e7a", 
			"capital": "minor", 
			"population": "7482", 
			"population_proper": "7482"
		}, 
		{
			"city": "Nisa", 
			"lat": "39.5167", 
			"lng": "-7.6500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Portalegre", 
			"capital": "minor", 
			"population": "7450", 
			"population_proper": "7450"
		}, 
		{
			"city": "Arraiolos", 
			"lat": "38.7229", 
			"lng": "-7.9843", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "\u00c9vora", 
			"capital": "minor", 
			"population": "7363", 
			"population_proper": "7363"
		}, 
		{
			"city": "Santa Marta de Penagui\u00e3o", 
			"lat": "41.2000", 
			"lng": "-7.7833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Vila Real", 
			"capital": "minor", 
			"population": "7356", 
			"population_proper": "7356"
		}, 
		{
			"city": "Borba", 
			"lat": "38.8000", 
			"lng": "-7.4500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "\u00c9vora", 
			"capital": "minor", 
			"population": "7333", 
			"population_proper": "7333"
		}, 
		{
			"city": "Vila Nova da Barquinha", 
			"lat": "39.4500", 
			"lng": "-8.4333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "7322", 
			"population_proper": "7322"
		}, 
		{
			"city": "Vila Nova de Foz C\u00f4a", 
			"lat": "41.0833", 
			"lng": "-7.1333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Guarda", 
			"capital": "minor", 
			"population": "7312", 
			"population_proper": "7312"
		}, 
		{
			"city": "Castel\u00f5es de Cepeda", 
			"lat": "41.2008", 
			"lng": "-8.3306", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "", 
			"population": "7299", 
			"population_proper": "7299"
		}, 
		{
			"city": "Poiares", 
			"lat": "40.2167", 
			"lng": "-8.2500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "minor", 
			"population": "7281", 
			"population_proper": "7281"
		}, 
		{
			"city": "Castro Verde", 
			"lat": "37.6976", 
			"lng": "-8.0819", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Beja", 
			"capital": "minor", 
			"population": "7276", 
			"population_proper": "7276"
		}, 
		{
			"city": "M\u00e9rtola", 
			"lat": "37.6333", 
			"lng": "-7.6500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Beja", 
			"capital": "minor", 
			"population": "7274", 
			"population_proper": "7274"
		}, 
		{
			"city": "Terras de Bouro", 
			"lat": "41.7167", 
			"lng": "-8.3000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "minor", 
			"population": "7253", 
			"population_proper": "7253"
		}, 
		{
			"city": "Redondo", 
			"lat": "38.6464", 
			"lng": "-7.5464", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "\u00c9vora", 
			"capital": "minor", 
			"population": "7031", 
			"population_proper": "7031"
		}, 
		{
			"city": "Castro Marim", 
			"lat": "37.2167", 
			"lng": "-7.4500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "minor", 
			"population": "6747", 
			"population_proper": "6747"
		}, 
		{
			"city": "Ribeira de Pena", 
			"lat": "41.5167", 
			"lng": "-7.8000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Vila Real", 
			"capital": "minor", 
			"population": "6544", 
			"population_proper": "6544"
		}, 
		{
			"city": "Portel", 
			"lat": "38.3000", 
			"lng": "-7.7000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "\u00c9vora", 
			"capital": "minor", 
			"population": "6428", 
			"population_proper": "6428"
		}, 
		{
			"city": "Carrazeda de Anci\u00e3es", 
			"lat": "41.2500", 
			"lng": "-7.3000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Bragan\u00e7a", 
			"capital": "minor", 
			"population": "6373", 
			"population_proper": "6373"
		}, 
		{
			"city": "Sabrosa", 
			"lat": "41.2651", 
			"lng": "-7.5751", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Vila Real", 
			"capital": "minor", 
			"population": "6361", 
			"population_proper": "6361"
		}, 
		{
			"city": "Tabua\u00e7o", 
			"lat": "41.1167", 
			"lng": "-7.5667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "6350", 
			"population_proper": "6350"
		}, 
		{
			"city": "Povoa\u00e7\u00e3o", 
			"lat": "37.7460", 
			"lng": "-25.2450", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Azores", 
			"capital": "", 
			"population": "6327", 
			"population_proper": "6327"
		}, 
		{
			"city": "Armamar", 
			"lat": "41.1167", 
			"lng": "-7.6833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "6297", 
			"population_proper": "6297"
		}, 
		{
			"city": "Figueira de Castelo Rodrigo", 
			"lat": "40.9000", 
			"lng": "-6.9667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Guarda", 
			"capital": "minor", 
			"population": "6260", 
			"population_proper": "6260"
		}, 
		{
			"city": "S\u00e3o Martinho", 
			"lat": "38.8125", 
			"lng": "-9.4208", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "", 
			"population": "6226", 
			"population_proper": "6226"
		}, 
		{
			"city": "Figueir\u00f3 dos Vinhos", 
			"lat": "39.9000", 
			"lng": "-8.2667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "minor", 
			"population": "6169", 
			"population_proper": "6169"
		}, 
		{
			"city": "Madalena", 
			"lat": "38.5356", 
			"lng": "-28.5234", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Azores", 
			"capital": "", 
			"population": "6049", 
			"population_proper": "6049"
		}, 
		{
			"city": "Monchique", 
			"lat": "37.3167", 
			"lng": "-8.6000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "minor", 
			"population": "6045", 
			"population_proper": "6045"
		}, 
		{
			"city": "Penela", 
			"lat": "40.0333", 
			"lng": "-8.3833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "minor", 
			"population": "5983", 
			"population_proper": "5983"
		}, 
		{
			"city": "Mur\u00e7a", 
			"lat": "41.4000", 
			"lng": "-7.4500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Vila Real", 
			"capital": "minor", 
			"population": "5952", 
			"population_proper": "5952"
		}, 
		{
			"city": "Vidigueira", 
			"lat": "38.2000", 
			"lng": "-7.8000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Beja", 
			"capital": "minor", 
			"population": "5932", 
			"population_proper": "5932"
		}, 
		{
			"city": "Olival", 
			"lat": "41.0711", 
			"lng": "-8.5272", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "", 
			"population": "5812", 
			"population_proper": "5812"
		}, 
		{
			"city": "Viana do Alentejo", 
			"lat": "38.3342", 
			"lng": "-8.0014", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "\u00c9vora", 
			"capital": "minor", 
			"population": "5743", 
			"population_proper": "5743"
		}, 
		{
			"city": "Oleiros", 
			"lat": "39.9167", 
			"lng": "-7.9167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Castelo Branco", 
			"capital": "minor", 
			"population": "5721", 
			"population_proper": "5721"
		}, 
		{
			"city": "Penamacor", 
			"lat": "40.1667", 
			"lng": "-7.1667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Castelo Branco", 
			"capital": "minor", 
			"population": "5682", 
			"population_proper": "5682"
		}, 
		{
			"city": "Vila do Porto", 
			"lat": "36.9450", 
			"lng": "-25.1450", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Azores", 
			"capital": "", 
			"population": "5552", 
			"population_proper": "5552"
		}, 
		{
			"city": "Aguiar da Beira", 
			"lat": "40.8180", 
			"lng": "-7.5414", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Guarda", 
			"capital": "minor", 
			"population": "5473", 
			"population_proper": "5473"
		}, 
		{
			"city": "Goleg\u00e3", 
			"lat": "39.4000", 
			"lng": "-8.4833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "5465", 
			"population_proper": "5465"
		}, 
		{
			"city": "Riachos", 
			"lat": "39.4453", 
			"lng": "-8.5142", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "", 
			"population": "5420", 
			"population_proper": "5420"
		}, 
		{
			"city": "Velas", 
			"lat": "38.6817", 
			"lng": "-28.2079", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Azores", 
			"capital": "", 
			"population": "5398", 
			"population_proper": "5398"
		}, 
		{
			"city": "Ourique", 
			"lat": "37.6500", 
			"lng": "-8.2250", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Beja", 
			"capital": "minor", 
			"population": "5389", 
			"population_proper": "5389"
		}, 
		{
			"city": "Vila do Bispo", 
			"lat": "37.0825", 
			"lng": "-8.9119", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "minor", 
			"population": "5258", 
			"population_proper": "5258"
		}, 
		{
			"city": "Vila Nova de Paiva", 
			"lat": "40.8500", 
			"lng": "-7.7333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "5176", 
			"population_proper": "5176"
		}, 
		{
			"city": "Terrujem", 
			"lat": "38.8511", 
			"lng": "-9.3747", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "", 
			"population": "5113", 
			"population_proper": "5113"
		}, 
		{
			"city": "Sousel", 
			"lat": "38.9532", 
			"lng": "-7.6757", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Portalegre", 
			"capital": "minor", 
			"population": "5074", 
			"population_proper": "5074"
		}, 
		{
			"city": "Fornos de Algodres", 
			"lat": "40.6167", 
			"lng": "-7.5333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Guarda", 
			"capital": "minor", 
			"population": "4989", 
			"population_proper": "4989"
		}, 
		{
			"city": "Mora", 
			"lat": "38.9333", 
			"lng": "-8.1500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "\u00c9vora", 
			"capital": "minor", 
			"population": "4978", 
			"population_proper": "4978"
		}, 
		{
			"city": "Caranguejeira", 
			"lat": "39.7500", 
			"lng": "-8.7000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "", 
			"population": "4972", 
			"population_proper": "4972"
		}, 
		{
			"city": "Nordeste", 
			"lat": "37.8333", 
			"lng": "-25.1500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Azores", 
			"capital": "", 
			"population": "4937", 
			"population_proper": "4937"
		}, 
		{
			"city": "Cuba", 
			"lat": "38.1500", 
			"lng": "-7.8833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Beja", 
			"capital": "minor", 
			"population": "4878", 
			"population_proper": "4878"
		}, 
		{
			"city": "Pampilhosa da Serra", 
			"lat": "40.0500", 
			"lng": "-7.9500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "minor", 
			"population": "4756", 
			"population_proper": "4756"
		}, 
		{
			"city": "Lajes", 
			"lat": "38.4000", 
			"lng": "-28.2500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Azores", 
			"capital": "", 
			"population": "4711", 
			"population_proper": "4711"
		}, 
		{
			"city": "Vimioso", 
			"lat": "41.5667", 
			"lng": "-6.5167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Bragan\u00e7a", 
			"capital": "minor", 
			"population": "4669", 
			"population_proper": "4669"
		}, 
		{
			"city": "Avis", 
			"lat": "39.0500", 
			"lng": "-7.8833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Portalegre", 
			"capital": "minor", 
			"population": "4571", 
			"population_proper": "4571"
		}, 
		{
			"city": "Mes\u00e3o Frio", 
			"lat": "41.1667", 
			"lng": "-7.8833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Vila Real", 
			"capital": "minor", 
			"population": "4433", 
			"population_proper": "4433"
		}, 
		{
			"city": "Valpa\u00e7os", 
			"lat": "41.6075", 
			"lng": "-7.3100", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Vila Real", 
			"capital": "minor", 
			"population": "4421", 
			"population_proper": "4421"
		}, 
		{
			"city": "G\u00f3is", 
			"lat": "40.1500", 
			"lng": "-8.1167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "minor", 
			"population": "4260", 
			"population_proper": "4260"
		}, 
		{
			"city": "Vila Nova de Milfontes", 
			"lat": "37.7167", 
			"lng": "-8.7833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Beja", 
			"capital": "", 
			"population": "4258", 
			"population_proper": "4258"
		}, 
		{
			"city": "Const\u00e2ncia", 
			"lat": "39.4833", 
			"lng": "-8.3333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "4056", 
			"population_proper": "4056"
		}, 
		{
			"city": "Sardoal", 
			"lat": "39.5333", 
			"lng": "-8.1667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "3939", 
			"population_proper": "3939"
		}, 
		{
			"city": "Arcozelo", 
			"lat": "41.7917", 
			"lng": "-8.5944", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viana do Castelo", 
			"capital": "", 
			"population": "3932", 
			"population_proper": "3932"
		}, 
		{
			"city": "Lorv\u00e3o", 
			"lat": "40.2594", 
			"lng": "-8.3168", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "", 
			"population": "3928", 
			"population_proper": "3928"
		}, 
		{
			"city": "Pedr\u00f3g\u00e3o Grande", 
			"lat": "39.9167", 
			"lng": "-8.1500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "minor", 
			"population": "3915", 
			"population_proper": "3915"
		}, 
		{
			"city": "Freixo de Espada \u00e0 Cinta", 
			"lat": "41.0833", 
			"lng": "-6.8000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Bragan\u00e7a", 
			"capital": "minor", 
			"population": "3780", 
			"population_proper": "3780"
		}, 
		{
			"city": "Calheta", 
			"lat": "38.6000", 
			"lng": "-28.0167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Azores", 
			"capital": "", 
			"population": "3773", 
			"population_proper": "3773"
		}, 
		{
			"city": "Arma\u00e7\u00e3o de P\u00eara", 
			"lat": "37.1000", 
			"lng": "-8.3667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "", 
			"population": "3770", 
			"population_proper": "3770"
		}, 
		{
			"city": "Vila Velha de R\u00f3d\u00e3o", 
			"lat": "39.6500", 
			"lng": "-7.6667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Castelo Branco", 
			"capital": "minor", 
			"population": "3521", 
			"population_proper": "3521"
		}, 
		{
			"city": "Marv\u00e3o", 
			"lat": "39.3942", 
			"lng": "-7.3772", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Portalegre", 
			"capital": "minor", 
			"population": "3512", 
			"population_proper": "3512"
		}, 
		{
			"city": "Vila de Rei", 
			"lat": "39.6833", 
			"lng": "-8.1500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Castelo Branco", 
			"capital": "minor", 
			"population": "3452", 
			"population_proper": "3452"
		}, 
		{
			"city": "Manteigas", 
			"lat": "40.4000", 
			"lng": "-7.5333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Guarda", 
			"capital": "minor", 
			"population": "3430", 
			"population_proper": "3430"
		}, 
		{
			"city": "Riba de Ave", 
			"lat": "41.3933", 
			"lng": "-8.3883", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "", 
			"population": "3425", 
			"population_proper": "3425"
		}, 
		{
			"city": "Fronteira", 
			"lat": "39.0500", 
			"lng": "-7.6500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Portalegre", 
			"capital": "minor", 
			"population": "3410", 
			"population_proper": "3410"
		}, 
		{
			"city": "Castelo de Vide", 
			"lat": "39.4167", 
			"lng": "-7.4500", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Portalegre", 
			"capital": "minor", 
			"population": "3407", 
			"population_proper": "3407"
		}, 
		{
			"city": "S\u00e3o Roque do Pico", 
			"lat": "38.5167", 
			"lng": "-28.3167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Azores", 
			"capital": "", 
			"population": "3388", 
			"population_proper": "3388"
		}, 
		{
			"city": "Monforte", 
			"lat": "39.0500", 
			"lng": "-7.4333", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Portalegre", 
			"capital": "minor", 
			"population": "3329", 
			"population_proper": "3329"
		}, 
		{
			"city": "Valado de Frades", 
			"lat": "39.5892", 
			"lng": "-9.0194", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "", 
			"population": "3308", 
			"population_proper": "3308"
		}, 
		{
			"city": "Castanheira de P\u00eara", 
			"lat": "40.0000", 
			"lng": "-8.2167", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "minor", 
			"population": "3191", 
			"population_proper": "3191"
		}, 
		{
			"city": "Arronches", 
			"lat": "39.1167", 
			"lng": "-7.2833", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Portalegre", 
			"capital": "minor", 
			"population": "3165", 
			"population_proper": "3165"
		}, 
		{
			"city": "S\u00e3o Vicente", 
			"lat": "32.7967", 
			"lng": "-17.0433", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Madeira", 
			"capital": "", 
			"population": "3136", 
			"population_proper": "3136"
		}, 
		{
			"city": "Trouxemil", 
			"lat": "40.2756", 
			"lng": "-8.4528", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "", 
			"population": "2999", 
			"population_proper": "2999"
		}, 
		{
			"city": "Ferreiros", 
			"lat": "41.6308", 
			"lng": "-8.3686", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "", 
			"population": "2879", 
			"population_proper": "2879"
		}, 
		{
			"city": "Carvoeiro", 
			"lat": "37.1000", 
			"lng": "-8.4667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "", 
			"population": "2721", 
			"population_proper": "2721"
		}, 
		{
			"city": "Porto Moniz", 
			"lat": "32.8667", 
			"lng": "-17.1667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Madeira", 
			"capital": "", 
			"population": "2711", 
			"population_proper": "2711"
		}, 
		{
			"city": "Mour\u00e3o", 
			"lat": "38.3333", 
			"lng": "-7.3667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "\u00c9vora", 
			"capital": "minor", 
			"population": "2663", 
			"population_proper": "2663"
		}, 
		{
			"city": "Barrancos", 
			"lat": "38.1307", 
			"lng": "-6.9761", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Beja", 
			"capital": "minor", 
			"population": "1834", 
			"population_proper": "1834"
		}, 
		{
			"city": "Caminha", 
			"lat": "41.8779", 
			"lng": "-8.8382", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viana do Castelo", 
			"capital": "minor", 
			"population": "1346", 
			"population_proper": "1346"
		}, 
		{
			"city": "Boticas", 
			"lat": "41.6889", 
			"lng": "-7.6650", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Vila Real", 
			"capital": "minor", 
			"population": "1065", 
			"population_proper": "1065"
		}, 
		{
			"city": "Barcelos", 
			"lat": "41.5347", 
			"lng": "-8.6150", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Loures", 
			"lat": "38.8309", 
			"lng": "-9.1684", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Santo Tirso", 
			"lat": "41.3428", 
			"lng": "-8.4775", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Porto", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Famalic\u00e3o", 
			"lat": "41.4144", 
			"lng": "-8.5222", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Cartaxo", 
			"lat": "39.1619", 
			"lng": "-8.7864", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Fund\u00e3o", 
			"lat": "40.1392", 
			"lng": "-7.5019", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Castelo Branco", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Oliveira de Azemeis", 
			"lat": "40.8400", 
			"lng": "-8.4764", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Ovar", 
			"lat": "40.8597", 
			"lng": "-8.6253", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Lagoa", 
			"lat": "37.1347", 
			"lng": "-8.4528", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Albufeira", 
			"lat": "37.0889", 
			"lng": "-8.2511", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Sintra", 
			"lat": "38.8144", 
			"lng": "-9.3837", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "\u00c1gueda", 
			"lat": "40.5745", 
			"lng": "-8.4480", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Peniche", 
			"lat": "39.3633", 
			"lng": "-9.3792", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Salvaterra de Magos", 
			"lat": "39.0253", 
			"lng": "-8.7933", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Cascais", 
			"lat": "38.6972", 
			"lng": "-9.4217", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Ponte da Barca", 
			"lat": "41.8078", 
			"lng": "-8.4194", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viana do Castelo", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Almod\u00f4var", 
			"lat": "37.5128", 
			"lng": "-8.0601", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Beja", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Alcoba\u00e7a", 
			"lat": "39.5522", 
			"lng": "-8.9775", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Oliveira do Hospital", 
			"lat": "40.3597", 
			"lng": "-7.8617", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Abrantes", 
			"lat": "39.4667", 
			"lng": "-8.2000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Santiago do Cac\u00e9m", 
			"lat": "38.0167", 
			"lng": "-8.7000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Set\u00fabal", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Cantanhede", 
			"lat": "40.3464", 
			"lng": "-8.5942", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Coimbra", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Gr\u00e2ndola", 
			"lat": "38.1833", 
			"lng": "-8.5667", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Set\u00fabal", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Mangualde", 
			"lat": "40.6058", 
			"lng": "-7.7658", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Arouca", 
			"lat": "40.9289", 
			"lng": "-8.2436", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Feira", 
			"lat": "40.9254", 
			"lng": "-8.5428", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Seia", 
			"lat": "40.4203", 
			"lng": "-7.7033", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Guarda", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Coruche", 
			"lat": "38.9581", 
			"lng": "-8.5283", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Chamusca", 
			"lat": "39.3594", 
			"lng": "-8.4808", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Crato", 
			"lat": "39.2844", 
			"lng": "-7.6444", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Portalegre", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Belmonte", 
			"lat": "40.3583", 
			"lng": "-7.3514", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Castelo Branco", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Vagos", 
			"lat": "40.5553", 
			"lng": "-8.6814", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Tondela", 
			"lat": "40.5164", 
			"lng": "-8.0808", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Gavi\u00e3o", 
			"lat": "39.4650", 
			"lng": "-7.9369", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Portalegre", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Santa Comba D\u00e3o", 
			"lat": "40.3981", 
			"lng": "-8.1303", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Alandroal", 
			"lat": "38.7020", 
			"lng": "-7.4031", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "\u00c9vora", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Mogadouro", 
			"lat": "41.3392", 
			"lng": "-6.7200", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Bragan\u00e7a", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Paredes de Coura", 
			"lat": "41.9111", 
			"lng": "-8.5597", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viana do Castelo", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Seixal", 
			"lat": "38.6428", 
			"lng": "-9.1061", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Set\u00fabal", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Amares", 
			"lat": "41.6309", 
			"lng": "-8.3512", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Alenquer", 
			"lat": "39.0531", 
			"lng": "-9.0092", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "M\u00eada", 
			"lat": "40.9631", 
			"lng": "-7.2631", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Guarda", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Vouzela", 
			"lat": "40.7231", 
			"lng": "-8.1122", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Ma\u00e7\u00e3o", 
			"lat": "39.5533", 
			"lng": "-7.9986", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Alf\u00e2ndega da F\u00e9", 
			"lat": "41.3431", 
			"lng": "-6.9611", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Bragan\u00e7a", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "S\u00e3o Pedro do Sul", 
			"lat": "40.7408", 
			"lng": "-8.0914", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Trofa", 
			"lat": "41.4878", 
			"lng": "-7.9613", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Alter do Ch\u00e3o", 
			"lat": "39.1974", 
			"lng": "-7.6589", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Portalegre", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Mort\u00e1gua", 
			"lat": "40.3947", 
			"lng": "-8.2328", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Vila Nova de Cerveira", 
			"lat": "41.9400", 
			"lng": "-8.7444", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viana do Castelo", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Arcos de Valdevez", 
			"lat": "41.8442", 
			"lng": "-8.4264", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viana do Castelo", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Alcanena", 
			"lat": "39.4589", 
			"lng": "-8.6689", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Santar\u00e9m", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Mealhada", 
			"lat": "40.3781", 
			"lng": "-8.4514", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Valen\u00e7a", 
			"lat": "42.0301", 
			"lng": "-8.6411", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viana do Castelo", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Sernancelhe", 
			"lat": "40.9003", 
			"lng": "-7.4942", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Vila Flor", 
			"lat": "41.3067", 
			"lng": "-7.1522", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Bragan\u00e7a", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Castelo de Paiva", 
			"lat": "41.0630", 
			"lng": "-8.2647", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Aveiro", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Penedono", 
			"lat": "40.9889", 
			"lng": "-7.3922", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Alij\u00f3", 
			"lat": "41.2768", 
			"lng": "-7.4749", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Vila Real", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Oliveira de Frades", 
			"lat": "40.7314", 
			"lng": "-8.1767", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Viseu", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Vizela", 
			"lat": "41.3828", 
			"lng": "-8.2647", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Braga", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Alvai\u00e1zere", 
			"lat": "39.8226", 
			"lng": "-8.3800", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Leiria", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Montalegre", 
			"lat": "41.8239", 
			"lng": "-7.7900", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Vila Real", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Alvito", 
			"lat": "38.2561", 
			"lng": "-7.9916", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Beja", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Alcoutim", 
			"lat": "37.4717", 
			"lng": "-7.4722", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Almeida", 
			"lat": "40.7257", 
			"lng": "-6.9061", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Guarda", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Aljezur", 
			"lat": "37.3192", 
			"lng": "-8.8033", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Faro", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Lourinh\u00e3", 
			"lat": "39.2425", 
			"lng": "-9.3122", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Lisboa", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}, 
		{
			"city": "Ferreira do Alentejo", 
			"lat": "38.0500", 
			"lng": "-8.1000", 
			"country": "Portugal", 
			"iso2": "PT", 
			"admin_name": "Beja", 
			"capital": "minor", 
			"population": "", 
			"population_proper": ""
		}
	]
}